### ISSUE TITLE
Card stop working in 2v

### ISSUE THREAD

**Issue by voggur** [boralyl/steam-wishlist#12]
The card stop displaying the list in version 2, sensors are there but nothing is displayed except the title of the card downgraded to 1.3.4 and the card is working again.   

Home Assistant Version: 2021.12.10

**Comment by boralyl** [comment]
@voggur Sorry, I should have mentioned in the v2.x.x release that the name of the sensor changed, so you will need to update your card to reference the new name.  It used to be `sensor.steam_wishlist` but it now includes your profile id, e.g. `sensor.steam_wishlist_<your-id>`.  If you click into the device for the steam wishlist integration from the integrations page and click on the Wishlist sensor you can find the new name.

![image](https://user-images.githubusercontent.com/109865/151711667-df0c0513-2d5d-401a-a718-ef9e56114234.png)

I'll update the release notes and README to make note of this.

**Comment by voggur** [comment]
Thank you it works again :)
