### ISSUE TITLE
Setup failed for custom integration steam_wishlist

### ISSUE THREAD

**Issue by justinmbrock** [boralyl/steam-wishlist#16]
**Describe the bug**
Setup fails with the latest version of Home Assistant due to a depreciated call (async_get_registry). This is from the logs:
```
Logger: homeassistant.setup
Source: setup.py:214
First occurred: 9:07:25 PM (1 occurrences)
Last logged: 9:07:25 PM

Setup failed for custom integration steam_wishlist: Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
```
This is an old depreciation message from last year for another integration I found:
```
2022-06-13 22:50:33 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for shelly using this method at custom_components/shelly/__init__.py, line 356: await self.hass.helpers.entity_registry.async_get_registry()
```

**To Reproduce**
1. Install the integration
2. Restart HA
3. See error in the log

**Expected behavior**
Integration setup completes and Steam Wishlist sensors are created.

**Screenshots**
 

**Home Assistant Version**:
Home Assistant 2023.5.0
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.1 - latest

**Custom Component Version**:
v2.2.3

**Additional context**

**Comment by boralyl** [comment]
Thank you for reporting, I somehow missed this :+1:

**Comment by boralyl** [comment]
This should be updated in [v2.2.4](https://github.com/boralyl/steam-wishlist/releases/tag/v2.2.4).
