### ISSUE TITLE
Possibility to add sorting option?

### ISSUE THREAD

**Issue by richardswesterhof** [boralyl/steam-wishlist#18]
Would it be possible to add a sorting option to the wishlist results? I would like to use the discount sort so I can see the top x games with the highest discount on my wishlist

**Comment by boralyl** [comment]
@richardswesterhof Are you referring to the values in this sensor? https://github.com/boralyl/steam-wishlist#sensorsteam_wishlist_your-profile-id

**Comment by boralyl** [comment]
I think you are asking for an option to allow sorting with this custom card: https://github.com/boralyl/steam-wishlist#displaying-in-lovelace

If that's what you are looking for I can add that to the card's repo over here: https://github.com/custom-cards/nintendo-wishlist-card

**Comment by boralyl** [comment]
Great, it would be much easier to add sorting options to the card, so I'll add them there.

**Comment by boralyl** [comment]
@richardswesterhof I added 2 new config options for sorting in the latest release: https://github.com/custom-cards/nintendo-wishlist-card/releases/tag/v2.3.0

Let me know if you have any problems.
