### ISSUE TITLE
Integration failing?

### ISSUE THREAD

**Issue by mainmachine** [boralyl/steam-wishlist#2]
Not much info I can give. Installed from HACS, went to Integrations, added steam-wishlist, entered my user account and got success message, restarted home assistant and got this:

```
Log Details (ERROR)

Logger: homeassistant.core
Source: custom_components/steam_wishlist/util.py:14
First occurred: 12:28:22 PM (15 occurrences)
Last logged: 2:48:23 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 104, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 170, in async_refresh
    update_callback()
  File "/config/custom_components/steam_wishlist/sensor_manager.py", line 147, in async_update_items
    steam_game = get_steam_game(game_id, game)
  File "/config/custom_components/steam_wishlist/util.py", line 14, in get_steam_game
    pricing: Dict[str, Any] = game["subs"][0]
TypeError: 'int' object is not subscriptable
```

This too:

```
Log Details (ERROR)

Logger: homeassistant.components.sensor
Source: custom_components/steam_wishlist/util.py:14
Integration: Sensor (documentation, issues)
First occurred: 12:18:24 PM (1 occurrences)
Last logged: 12:18:24 PM
Error while setting up steam_wishlist platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/steam_wishlist/sensor.py", line 13, in async_setup_entry
    "sensor", async_add_entities
  File "/config/custom_components/steam_wishlist/sensor_manager.py", line 126, in async_register_component
    await self.coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 170, in async_refresh
    update_callback()
  File "/config/custom_components/steam_wishlist/sensor_manager.py", line 147, in async_update_items
    steam_game = get_steam_game(game_id, game)
  File "/config/custom_components/steam_wishlist/util.py", line 14, in get_steam_game
    pricing: Dict[str, Any] = game["subs"][0]
TypeError: 'int' object is not subscriptable
```

**Comment by rvdbeek** [comment]
I installed it also via Hacs, and I have exactly the same error in my log.

**Comment by boralyl** [comment]
Would you mind sharing your steam username?  The json response must be slightly different than I'm expecting, as I don't get this error on any games on my wish list.

**Comment by TonedAUS** [comment]
I am getting this issue as well.

I also reset my password just to make sure it wasn't a password issue.  My steam username is TonedAU

**Comment by boralyl** [comment]
Thanks @TonedAUS , I was able to reproduce.  It appears the component doesn't handle the case where a wishlist doesn't have any items on it.

**Comment by boralyl** [comment]
Just released v1.1.3 in HASC that should fix the issue.  Let me know if it doesn't.  You will have to remove the existing integration and re-add it.

**Comment by TonedAUS** [comment]
The error has gone and the sensor is now appearing.  I have 17 items in my wish list and 3 of them are on sale but nothing is showing in the sensor.  It is saying there are 0 on sale.

**Comment by boralyl** [comment]
Is there only a single entity created?  When I try to view your wishlist, I see an empty list https://store.steampowered.com/wishlist/id/TonedAU/  I'm wondering if this is a regional issue.  What does the URL look like for your wishlist in steam?

**Comment by TonedAUS** [comment]
Yeah there is only sensor.steam_wishlist 
That is the correct wishlist URL.

**Comment by boralyl** [comment]
To be clear, when you go to that URL you can see all 17 games on your wishlist?

**Comment by TonedAUS** [comment]
Yes that is correct it add's #sort=order on the end though but I don't that would be causing the issue.

Do you see them when you go to here?

https://store.steampowered.com/wishlist/profiles/76561198001860008

**Comment by rvdbeek** [comment]
I have the same 'rvdbeek' is my steam name. I see nothing on the wishlist via the url, but I see games on it via steam app. My profile is public

**Comment by TonedAUS** [comment]
I worked out what the issue is.  Even though my profile was set to public, Game Details was set to friends only.  I changed that to public as well and now HA is seeing my wishlist and all the games are now showing.

**Comment by rvdbeek** [comment]
Haha, same here, I can see your games now, thank you both

**Comment by TonedAUS** [comment]
now just got to work out what is the best card to use  :)

**Comment by boralyl** [comment]
Ah!  Thanks for the info.  I'll update the README to specify that you have to have to set Game Details to public for this component to work.

**Comment by rvdbeek** [comment]
> now just got to work out what is the best card to use :)

And what did you use?

**Comment by TonedAUS** [comment]
nothing as yet, haven't had a chance to have a play around, but something like the Sonarr/Radarr upcoming cards would be good

**Comment by boralyl** [comment]
Looks like the card I made for the nintendo switch wishlist also works with this component since they store data in a similar way: https://github.com/custom-cards/nintendo-wishlist-card

It's heavily based on the upcoming media card, so it should suite your needs.

```yaml
  - type: custom:nintendo-wishlist-card
    entity: sensor.steam_wishlist
    title: Steam Wishlist
    image_style: backgroundart
    max: 10
```

![image](https://user-images.githubusercontent.com/109865/80817331-14db0d00-8b86-11ea-84f5-b604047493a8.png)

**Comment by rvdbeek** [comment]
Nice.. Will have a look later, thanks!
