### ISSUE TITLE
Sensor Steam

### ISSUE THREAD

**Issue by Link0Darck** [boralyl/steam-wishlist#21]
Good morning,
I have a simple question: how did you create the steam sensor?
Thanks in advance

**Comment by boralyl** [comment]
To create the steam sensor you need to first install the custom integration.  You can refer to the README for the 2 methods of installation: https://github.com/boralyl/steam-wishlist?tab=readme-ov-file#hacs-installation

After the integration is installed you can go to the integrations page in your settings and click on the `ADD INTEGRATION` button, then search for "Steam Wishlist".  From there you will be guided through the process via the UI.  After you've done that the sensor will be created.

**Comment by Link0Darck** [comment]
Thank you, I just understood, sorry for the inconvenience
