### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by axellencyDE** [boralyl/steam-wishlist#22]
I implemented this today and it worked fine, pulling all the games on my wishlist. Hours ago, though, I removed some of the games on my wishlist, yet they still appear in this integration. How often is this refreshed? Not sure if this is a bug or expected behaviour.

**Comment by boralyl** [comment]
The sensor updates every hour. At that time it should remove sensors no longer in your wishlist. If that's not the case let me know and I will take a look next week. Thanks!

**Comment by axellencyDE** [comment]
Thanks for your response! I don’t really understand the behavior at this point, but it doesn’t seem to be working as intended at least in my installation. It took some hours to reflect the changes in my wishlist, correctly removing sensors. In the meantime, one sale has ended (sensor correctly removed) and one started (no sensor for that). Is there any information I can provide you with that would help shed some light into this?

**Comment by axellencyDE** [comment]
More context: The games I removed still have their sensor, just with an ‚unavailable‘ status now. That’s also the case for the game I actually still have on my wishlist, but is no longer on sale. The steam wishlist has status 0 now, although there is one game on sale for about a day now.

**Comment by boralyl** [comment]
When an item is removed from your wish list, the entity gets removed.  This will cause it's status to become `unavailable`.  (Need to do a little research to see if this is the correct behavior or if there is someway to completely remove it).

I might need some more information to debug your other issue where a game is on sale, but it's not showing up as such in the sensor.  Could you share a link to the game?

**Comment by axellencyDE** [comment]
Okay, than I misunderstood how the integration works. That means, if I were to delete dozens of games from my wishlist, I would end up with dozens of "orphaned" entities with `unavailable` status, right? Just went through some threads looking for an automation to delete entities of a specific device when their status becomes `unavailable`, but that doesn't seem to be easily possible in HA.

The game on sale that was not showing up unfortunately is no longer on sale now. For testing purposes, I've added Red Dead Redemption II to the wishlist, which is now showing up as an entity, and the status correctly is shown as `true` right now. So... I don't know what caused the hiccups, but currently, it seems to be working as intended. I would keep you posted here, if something changes. :) Thanks!

**Comment by boralyl** [comment]
I made a few small tweaks so that the device will show all related sensors.  Items removed from your wishlist will not show up there.  (although they'll still show as unavailable if you look in the dev tools).  https://github.com/boralyl/steam-wishlist/releases/tag/v2.4.0

![image](https://github.com/boralyl/steam-wishlist/assets/109865/f0bb783f-73fd-4ca2-8e32-677003d62c47)
