### ISSUE TITLE
Price not displaying correctly

### ISSUE THREAD

**Issue by Andrewpaps** [boralyl/steam-wishlist#24]
**Describe the bug**
Price not displaying correctly.

**To Reproduce**
1. Install Steam Wishlist custom component
2. Install Upcoming Media custom component (version 0.4.4)
3. Copy & paste example yaml lovelace config

**Expected behavior**
Price displayed.

![image](https://github.com/boralyl/steam-wishlist/assets/71562383/d00d83cc-c40b-44a0-b1fe-5dabab9f3c11)

**Home Assistant Version**:
Current (2024.6.2)

**Custom Component Version**:
Current (v2.4.0)

**Comment by boralyl** [comment]
Thanks for reporting @Andrewpaps .  It appears the integration is setting the price attribute correctly if you look at the state attributes in the developer tools:
![image](https://github.com/boralyl/steam-wishlist/assets/109865/5d75176e-f0ed-4f69-8847-2c23c992d488)

So the issue would likely be with the [upcoming-media-card ](https://github.com/custom-cards/upcoming-media-card) you are using.  I would open up this issue in that repo to get it resolved :+1:

**Comment by Andrewpaps** [comment]
Ah, I thought that may be the case. I did also have a look in the Developer Tools and saw the same, which lead to the confusion.

I will move the issue to that repo. Thanks!

**Comment by Andrewpaps** [comment]
Just commenting for posterity and anyone else who comes across this issue: 

I now see that the issue was I was using the original (unmaintained?) repo of upcoming-media-card as provided by HACS and not the new one that has since been forked that you have linked here. The new fork is the one with support for Steam Wishlist and has subsequently solved the issue!

**Comment by boralyl** [comment]
Thanks for adding that additional context!
