### ISSUE TITLE
Prices unavailable 

### ISSUE THREAD

**Issue by velodromen** [boralyl/steam-wishlist#25]
**Describe the bug**
There are no prices listed in the card. The other parameters are working. Followed the guidance on the website to the point.

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot_20240629-161920](https://github.com/boralyl/steam-wishlist/assets/15056904/c4c029c7-0db7-4dd4-b3a3-2d6a0db78438)

**Home Assistant Version**:
Latest

**Custom Component Version**:
Latest

**Additional context**

**Comment by boralyl** [comment]
The display issue is related to the custom card, I believe you are using an unmaintained version.  See this comment: https://github.com/boralyl/steam-wishlist/issues/24#issuecomment-2163521363

**Comment by velodromen** [comment]
Thanks, that was indeed the case. After changing to the version you linked to in your post it the price appears.

Thanks once again!

//Johan
________________________________
Från: Aaron Godfrey ***@***.***>
Skickat: den 29 juni 2024 19:05
Till: boralyl/steam-wishlist ***@***.***>
Kopia: velodromen ***@***.***>; Author ***@***.***>
Ämne: Re: [boralyl/steam-wishlist] Prices unavailable (Issue #25)


The display issue is related to the custom card, I believe you are using an unmaintained version. See this comment: #24 (comment)<https://github.com/boralyl/steam-wishlist/issues/24#issuecomment-2163521363>
