### ISSUE TITLE
Async forward error

### ISSUE THREAD

**Issue by Krispkiwi** [boralyl/steam-wishlist#26]
Getting this error in the logs

entry_id: 01J50KJ4D226C87FE1AEWKXCKM, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Home Assistant Version**:
Latest
**Custom Component Version**:
Latest
**Additional context**

**Comment by boralyl** [comment]
Thanks for reporting!  https://github.com/boralyl/steam-wishlist/releases/tag/v2.4.1
