### ISSUE TITLE
Showing/hiding elements

### ISSUE THREAD

**Issue by justbest23** [boralyl/steam-wishlist#28]
I cannot seem to find a way to show/hide elements of the card. For example, I want to hide the release date, but I can't figure out how?
![image](https://github.com/user-attachments/assets/c7781eb2-e79c-4b93-a9cc-278275c65c17)

**Comment by boralyl** [comment]
@justbest23 This component only handles retrieving data and creating sensors.  If you are using the upcoming media card, you'll need to open an issue in that project: https://github.com/custom-cards/upcoming-media-card

**Comment by justbest23** [comment]
Thanks! I see you get a ton of these! Maybe put something on the main page that says that any issues shouldn't go here!
