### ISSUE TITLE
"Could not find a Steam profile with the provided ID."

### ISSUE THREAD

**Issue by philipjholm** [boralyl/steam-wishlist#29]
**Describe the bug**
Is this integration still working? I had it for a long time working and then just a little while ago it seems it stopped working. I removed it and tried to re-install it but when doing the setup by using profile ID I just get "Could not find a Steam profile with the provided ID". I've made sure the profile is public and is using the correct ID. 
If I use the profile name option instead I get "Could not find a steam account associated with the provided name or your profile is not public, see https://github.com/boralyl/steam-wishlist#pre-installation".

**To Reproduce**
1. Download through HACS
2. Go to Settings -> Devices & integrations -> Add integration
3. Find Steam Wishlist
4. Add profile id OR name and click submit
5. Get above error.

**Home Assistant Version**:
Core 2024.11.3

**Custom Component Version**:
2.4.1

**Comment by boralyl** [comment]
@philipjholm  Thanks for pointing this out.  It appears the URL I was using to get wishlist data has been removed.  As far as I can tell the only way to get the data would be to parse html which is a little gross and might not provide all of the data the integration was previously providing.

This means that the integration will no longer work for the moment.  I'm looking into alternative methods.

**Comment by philipjholm** [comment]
Thanks for looking into it!

**Comment by boralyl** [comment]
I've got a branch where I'm working on a fix.  I don't know exactly how long it will take as it's slightly more complicated then the single endpoint I was using previously, but it shouldn't be too bad to implement.

**Comment by philipjholm** [comment]
@boralyl No stress, but sounds awesome 😁

**Comment by boralyl** [comment]
@philipjholm I just release [v3.0.0](https://github.com/boralyl/steam-wishlist/releases/tag/v3.0.0) which will allow you to add the integration again.

If you already have it setup, you will need to delete it, then re-add it so that you can reconfigure it with a web api key.

**Comment by philipjholm** [comment]
@boralyl Works perfectly for me! Thanks a lot, friend.
