### ISSUE TITLE
New Integrationen with api key

### ISSUE THREAD

**Issue by Johnyboy1984** [boralyl/steam-wishlist#31]
I cannot install this integration because the Steam integration in Home Assistant already requires an API key and I cannot create another one. If you enter the existing API key, it will not work in your Steam Wishlist integration.

Unexpected error fetching steam_wishlist data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/steam_wishlist/sensor_manager.py", line 57, in _async_fetch_data
    item["appid"] for item in wishlist_data["response"]["items"]
                              ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'

**Comment by boralyl** [comment]
I don't believe it's related to having setup the steam integration.  I have both the steam integration and this custom integration setup at the same time.

This is a little tricky to debug, could you confirm that you get a successful response with this url:

```
https://api.steampowered.com/ISteamUser/ResolveVanityURL/v1/?key=<your-api-key>&vanityurl=<your-account-name>
```
If it's successful it should return something like:

```json
{
  "response": {
    "steamid": "123456789",
    "success": 1
  }
}
```

If that returns a successful response, could you also make sure this URL returns data as expected:

```
https://api.steampowered.com/IWishlistService/GetWishlist/v1?key=<your-api-key>&steamid=<your-steamid-from-the-response-of-the-previous-url>
```
If successful it should return something like:

```json
{
  "response": {
    "items": [
      {
        "appid": 305050,
        "priority": 0,
        "date_added": 1623646592
      },
      {
        "appid": 347800,
        "priority": 0,
        "date_added": 1668103596
      }
    ]
  }
}
```

**Comment by Johnyboy1984** [comment]
> ttps://api.steampowered.com/ISteamUser/ResolveVanityURL/v1/?key=<your-api-key>&vanityurl=<your-account-name

![image](https://github.com/user-attachments/assets/4fcb736b-a232-4e28-bb81-848b677fc3ea)

**Comment by Johnyboy1984** [comment]
If I enter the existing API key, this appears in Home Assistant:

![image](https://github.com/user-attachments/assets/3be4e0b4-8d49-4c2c-b121-db4ed0ff8b7e)

**Comment by boralyl** [comment]
> > ttps://api.steampowered.com/ISteamUser/ResolveVanityURL/v1/?key=&vanityurl=<your-account-name
> 
> ![image](https://private-user-images.githubusercontent.com/96473114/393634083-4fcb736b-a232-4e28-bb81-848b677fc3ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2ODQ0MjQsIm5iZiI6MTczMzY4NDEyNCwicGF0aCI6Ii85NjQ3MzExNC8zOTM2MzQwODMtNGZjYjczNmItYTIzMi00ZTI4LWJiODEtODQ4YjY3N2ZjM2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE4NTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYTUzNjNkOTE0NDQ0ZGZmMDRmMzFlYzI2YzhjNWVlNjNmMjEzODQ0YTEzZTM5NmY5NTYzYmQzN2ZmYzBmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ao81cjzEDOvXyjZdXU_Q7F7GkyKvoanLMjxuAvzxgSE)

Based on your 2nd screenshot it appears that the first url returns a successful response since it shows your steam id in parenthesis.

So help debug, I'd need the response of this url (replace `<your-api-key>` with your real api key):

`https://api.steampowered.com/IWishlistService/GetWishlist/v1?key=<your-api-key>&steamid=76561197960522903`

**Comment by Johnyboy1984** [comment]
> https://api.steampowered.com/IWishlistService/GetWishlist/v1?key=<your-api-key>&steamid=76561197960522903

![image](https://github.com/user-attachments/assets/d59a5343-de13-4123-a9b3-130e2d802be2)

**Comment by lbandi2** [comment]
I also get the same exact empty response.

`{"response":{}}`

**Comment by boralyl** [comment]
Thanks for the response.  I thought maybe it had to do with privacy settings as previously the `Game Details` setting had to be public in order to retrieve the wish list data.  I wouldn't think that would be required with an api key, and in my testing when I made my profile private it still pulled data as expected.

But you could try setting "Game details" to "Public" under the Privacy Settings when editing your profile and report back if that changed anything.

Somewhat at a loss at the moment as to why it can't fetch your wish list.

**Comment by Johnyboy1984** [comment]
I changed something else in Steam, but unfortunately it didn't result in it retrieving the wishlist.

**Comment by boralyl** [comment]
> I changed something else in Steam, but unfortunately it didn't result in it retrieving the wishlist.

Thanks for trying.  I unfortunately don't have any other suggestions.  It works for some folks and not others for some reason.  There really isn't another way to get the wishlist data besides the endpoint I"m currently using: https://steamapi.xpaw.me/#IWishlistService/GetWishlist

**Comment by lbandi2** [comment]
V3.01 fixed it for me.

**Comment by Johnyboy1984** [comment]
Thank you very much for your efforts to solve the problem that not everyone has. With your new fix it works straight away. Thank you again. I wish you a wonderful Christmas. Best wishes, Johnyboy1984
